-- Level 1
local levelDataTable = {{2},--<-- contains the level 
                        {4},
                        {6},
                        {0},
                        {0},
                        {0},
                        {0},
                        {8},
                        {4,8},
                        {2,6},
                        {0},
                        {0},
                        {0},
                        {1,3,5,7},
                        {0},
                        {2,4,6,8},
                        {0},
                        {2,4,6,8},
                        {0},
                        {0},
                        {1},
                        {3},
                        {7},
                        {0},
                        {5},
                        {0},
                        {0},
                        {2,4,8},
                        {0},
                        {6},
                        {6},
                        {6},
                        {0},
                        {0},
                        {0},
                        {0},
                        {0}}
-- print ("levelData was retrieved")
return levelDataTable